apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-proof-section
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: mmalabugin.ru
      http:
        paths:
          - path: /SocialProofSection
            pathType: Prefix
            backend:
              service:
                name: social-proof-section
                port:
                  number: 80
  tls:
    - hosts:
        - mmalabugin.ru
      secretName: main-page-tls
