apiVersion: v1
kind: Service
metadata:
  name: social-proof-section
  namespace: default
spec:
  selector:
    app: social-proof-section-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
